name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types:
      - vercel.deployment.success

env:
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers

jobs:
  test-local:
    if: github.event_name != 'repository_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests against local build
        run: |
          npm run start &
          # Wait for the server to start
          npx wait-on http://localhost:3000
          npm run test:e2e
        env:
          CI: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-results-local
          path: |
            test-results/
            playwright-report/
          retention-days: 7

  test-vercel-deployment:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.git.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci && npx playwright install --with-deps chromium

      - name: Run Playwright tests against Vercel deployment
        run: npm run test:e2e
        env:
          CI: true
          BASE_URL: ${{ github.event.client_payload.url }}

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-results-vercel
          path: |
            test-results/
            playwright-report/
          retention-days: 7
